### ISSUE TITLE
SyntaxError in index.js ?

### ISSUE THREAD

**Issue by vinsse2001** [mflorence99/el-3270#9]
Hi ! I'm trying to install el-3270 on Ubuntu (18.2 Sonya), so I installed/updated nodejs and npm : 
```
$ sudo apt install nodejs npm
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
npm est déjà la version la plus récente (3.5.2-0ubuntu4).
nodejs est déjà la version la plus récente (4.2.6~dfsg-1ubuntu4.2).
nodejs passé en « installé manuellement ».
0 mis à jour, 0 nouvellement installés, 0 à enlever et 51 non mis à jour.
```
and launch after `$ npm install`, but I have a SyntaxError : 
```
el-3270/node_modules/electron-rebuild/node_modules/fs-extra/lib/fs/index.js:93
exports.write = function (fd, buffer, ...args) {
                                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vincent/Dev/3270/el-3270/node_modules/electron-rebuild/node_modules/fs-extra/lib/index.js:6:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
I joined index.js and npm-debug.log, thanks for help !
[npm-debug.log](https://github.com/mflorence99/el-3270/files/3064357/npm-debug.log)
[index.js.zip](https://github.com/mflorence99/el-3270/files/3064359/index.js.zip)

**Comment by vinsse2001** [comment]
the index.js I attached is original, here is the rebuild one (/home/vincent/Dev/3270/el-3270/node_modules/electron-rebuild/node_modules/fs-extra/lib/fs/index.js)
[index.js.zip](https://github.com/mflorence99/el-3270/files/3064621/index.js.zip)

**Comment by mflorence99** [comment]
Hi Vincent -- that `index.js` file is in Node.js itself, so I'm a bit puzzled. When you say you launched the app, what exact command did you run? Referring to the `readme`, you must run two commands in dev mode, each from a separate command-line session. First, `npm run serve` then `npm run test`. From which did your error originate?

**Comment by vinsse2001** [comment]
sorry, i think tha I need to resolve first some problems about web connections on the server, because, after configuring npm (I added some informations in .npmrc to use artifactory, installed in my company) I don't have the same error. Now, the error is about impossibility to join github...
I'm trying to find what is needed more in configuration :) !

**Comment by mflorence99** [comment]
Good luck! Please let me know if I can help with any advice.
